version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Get info
          command: docker info
      - run:
          name: Build the custom container
          command: docker build -t $DOCKER_USER/datingfourthaisites  .
          no_output_timeout: 4h

