version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Get info
          command: docker info
      - run:
          name: Build the custom container
          command:  docker build -t benmarwick/datingfourthaisites  https://raw.githubusercontent.com/benmarwick/datingfourthaisites/master/Dockerfile
          no_output_timeout: 4h

