name: Render manuscript on Docker
on: [push]
jobs:
  my_job: 
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
      - uses: actions/checkout@v1
      - name: Install prereqs
        run: sudo apt-get update && sudo apt-get install libgdal-dev libudunits2-dev -y
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      - name: Render mansucript
        run: |-
          Rscript -e "code', glob='*.Rmd', recurse=TRUE), rmarkdown::render, envir = globalenv())"

## remarkably(?), we can use the standard checkout action, actions/checkout@v1
## even inside this Docker container.
